In [10]:
import sys
import pandas as pd
import pycaret as pc
from pycaret.classification import *

In [11]:
print('python',sys.version)
print('pycaret',pc.__version__)

python 3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)]
pycaret 3.0.0

In [12]:
df = pd.read_csv('log2.csv')
df.head()

,Source Port,Destination Port,NAT Source Port,NAT Destination Port,Action,Bytes,Bytes Sent,Bytes Received,Packets,Elapsed Time (sec),pkts_sent,pkts_received
0,57222,53,54587,53,allow,177,94,83,2,30,1,1
1,56258,3389,56258,3389,allow,4768,1600,3168,19,17,10,9
2,6881,50321,43265,50321,allow,238,118,120,2,1199,1,1
3,50553,3389,50553,3389,allow,3327,1438,1889,15,17,8,7
4,50002,443,45848,443,allow,25358,6778,18580,31,16,13,18

In [13]:
s = setup(df, target = 'Action'
          ,categorical_features=['Source Port','Destination Port','NAT Source Port','NAT Destination Port']
          ,fix_imbalance = True
          ,normalize = True
          )

Warning: No categorical columns found. Calling 'transform' will only return input data.

In [14]:
pull()

                    Description                                      Value
0                    Session id                                       8770
1                        Target                                     Action
2                   Target type                                 Multiclass
3                Target mapping  allow: 0, deny: 1, drop: 2, reset-both: 3
4           Original data shape                                (65532, 12)
5        Transformed data shape                               (125052, 12)
6   Transformed train set shape                               (105392, 12)
7    Transformed test set shape                                (19660, 12)
8              Numeric features                                          7
9          Categorical features                                          4
10                   Preprocess                                       True
11              Imputation type                                     simple
12           Numeric imputation                                       mean
13       Categorical imputation                                       mode
14     Maximum one-hot encoding                                         25
15              Encoding method                                       None
16                Fix imbalance                                       True
17         Fix imbalance method                                      SMOTE
18                    Normalize                                       True
19             Normalize method                                     zscore
20               Fold Generator                            StratifiedKFold
21                  Fold Number                                         10
22                     CPU Jobs                                         -1
23                      Use GPU                                      False
24               Log Experiment                                      False
25              Experiment Name                           clf-default-name
26                          USI                                       14e6

In [17]:
models()

,Name,Reference,Turbo
ID,,,
lr,Logistic Regression,sklearn.linear_model._logistic.LogisticRegression,True
knn,K Neighbors Classifier,sklearn.neighbors._classification.KNeighborsCl...,True
nb,Naive Bayes,sklearn.naive_bayes.GaussianNB,True
dt,Decision Tree Classifier,sklearn.tree._classes.DecisionTreeClassifier,True
svm,SVM - Linear Kernel,sklearn.linear_model._stochastic_gradient.SGDC...,True
rbfsvm,SVM - Radial Kernel,sklearn.svm._classes.SVC,False
gpc,Gaussian Process Classifier,sklearn.gaussian_process._gpc.GaussianProcessC...,False
mlp,MLP Classifier,sklearn.neural_network._multilayer_perceptron....,False
ridge,Ridge Classifier,sklearn.linear_model._ridge.RidgeClassifier,True
rf,Random Forest Classifier,sklearn.ensemble._forest.RandomForestClassifier,True
qda,Quadratic Discriminant Analysis,sklearn.discriminant_analysis.QuadraticDiscrim...,True
ada,Ada Boost Classifier,sklearn.ensemble._weight_boosting.AdaBoostClas...,True
gbc,Gradient Boosting Classifier,sklearn.ensemble._gb.GradientBoostingClassifier,True
lda,Linear Discriminant Analysis,sklearn.discriminant_analysis.LinearDiscrimina...,True
et,Extra Trees Classifier,sklearn.ensemble._forest.ExtraTreesClassifier,True
xgboost,Extreme Gradient Boosting,xgboost.sklearn.XGBClassifier,True
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMClassifier,True
dummy,Dummy Classifier,sklearn.dummy.DummyClassifier,True

In [16]:
best_model = compare_models()

Initiated  . . . . . . . . . . . . . . . . . .              00:22:26
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

In [18]:
pull()

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
xgboost,Extreme Gradient Boosting,0.9977,0.9997,0.9977,0.9981,0.9979,0.9960,0.9960,3.595
lightgbm,Light Gradient Boosting Machine,0.9973,0.9997,0.9973,0.9982,0.9977,0.9953,0.9953,0.984
et,Extra Trees Classifier,0.9971,0.9995,0.9971,0.9976,0.9973,0.9950,0.9950,1.139
rf,Random Forest Classifier,0.9968,0.9997,0.9968,0.9982,0.9974,0.9944,0.9944,1.304
dt,Decision Tree Classifier,0.9966,0.9982,0.9966,0.9975,0.9970,0.9941,0.9941,0.550
nb,Naive Bayes,0.9912,0.9990,0.9912,0.9970,0.9940,0.9849,0.9850,0.529
gbc,Gradient Boosting Classifier,0.9899,0.9997,0.9899,0.9981,0.9936,0.9826,0.9827,8.451
knn,K Neighbors Classifier,0.9888,0.9973,0.9888,0.9972,0.9928,0.9808,0.9810,0.699
lr,Logistic Regression,0.9164,0.9977,0.9164,0.9888,0.9449,0.8605,0.8688,1.591
svm,SVM - Linear Kernel,0.9026,0.0000,0.9026,0.9876,0.9334,0.8381,0.8494,0.584
ada,Ada Boost Classifier,0.8660,0.9991,0.8660,0.9706,0.8713,0.7866,0.8178,1.088
ridge,Ridge Classifier,0.7676,0.0000,0.7676,0.9130,0.8052,0.6406,0.6708,0.538
lda,Linear Discriminant Analysis,0.7592,0.9879,0.7592,0.9104,0.7983,0.6301,0.6623,0.567
qda,Quadratic Discriminant Analysis,0.5766,0.8569,0.5766,0.8024,0.5769,0.3672,0.4611,0.553
dummy,Dummy Classifier,0.5744,0.5000,0.5744,0.3299,0.4191,0.0000,0.0000,0.545

In [19]:
print(best_model)

XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=-1, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [20]:
tune_model, tuner = tune_model(best_model,return_tuner=True,choose_better = True)

Initiated  . . . . . . . . . . . . . . . . . .              00:29:34
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [21]:
print(tuner)

RandomizedSearchCV(cv=StratifiedKFold(n_splits=10, random_state=None, shuffle=False),
                   error_score=nan,
                   estimator=Pipeline(memory=FastMemory(location=C:\Users\novm1\AppData\Local\Temp\joblib),
                                      steps=[('label_encoding',
                                              TransformerWrapperWithInverse(exclude=None,
                                                                            include=None,
                                                                            transformer=LabelEncoder())),
                                             ('numerical_imputer',
                                              TransformerWrapper(exclude=None,...
                                                                         0.4,
                                                                         0.5,
                                                                         0.7, 1,
                                                                         2, 3,
                                                                         4, 5,
                                                                         10],
                                        'actual_estimator__scale_pos_weight': [0.0,
                                                                               0.1,
                                                                               0.2,
                                                                               0.3,
                                                                               0.4,
                                                                               0.5,
                                                                               0.6,
                                                                               0.7,
                                                                               0.8,
                                                                               0.9,
                                                                               1.0,
                                                                               1.1,
                                                                               1.2,
                                                                               1.3,
                                                                               1.4,
                                                                               1.5,
                                                                               1.6,
                                                                               1.7,
                                                                               1.8,
                                                                               1.9,
                                                                               2.0,
                                                                               2.1,
                                                                               2.2,
                                                                               2.3,
                                                                               2.4,
                                                                               2.5,
                                                                               2.6,
                                                                               2.7,
                                                                               2.8,
                                                                               2.9, ...],
                                        'actual_estimator__subsample': [0.2,
                                                                        0.3,
                                                                        0.5,
                                                                        0.7,
                                                                        0.9,
                                                                        1]},
                   pre_dispatch='2*n_jobs', random_state=8770, refit=False,
                   return_train_score=False, scoring='accuracy', verbose=1)

In [22]:
bagged_dt = ensemble_model(best_model,choose_better = True)

Initiated  . . . . . . . . . . . . . . . . . .              00:36:45
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

In [23]:
print(bagged_dt)

XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=-1, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [24]:
boosted_dt = ensemble_model(best_model,method = 'Boosting',choose_better = True)

Initiated  . . . . . . . . . . . . . . . . . .              00:47:37
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

In [25]:
pull()

      Accuracy  AUC  Recall   Prec.      F1  Kappa  MCC
Fold
0       0.5743  0.5  0.5743  0.3298  0.4190    0.0  0.0
1       0.5743  0.5  0.5743  0.3298  0.4190    0.0  0.0
2       0.5744  0.5  0.5744  0.3300  0.4192    0.0  0.0
3       0.5742  0.5  0.5742  0.3297  0.4189    0.0  0.0
4       0.5742  0.5  0.5742  0.3297  0.4189    0.0  0.0
5       0.5744  0.5  0.5744  0.3300  0.4192    0.0  0.0
6       0.5744  0.5  0.5744  0.3300  0.4192    0.0  0.0
7       0.5744  0.5  0.5744  0.3300  0.4192    0.0  0.0
8       0.5744  0.5  0.5744  0.3300  0.4192    0.0  0.0
9       0.5744  0.5  0.5744  0.3300  0.4192    0.0  0.0
Mean    0.5744  0.5  0.5744  0.3299  0.4191    0.0  0.0
Std     0.0001  0.0  0.0001  0.0001  0.0001    0.0  0.0

In [26]:
print(boosted_dt)

XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=-1, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [2]:
# load dataset
from pycaret.datasets import get_data
data = get_data('log2')

# init setup
from pycaret.classification import *
clf1 = setup(data=data, target = 'Action'
          ,categorical_features=['Source Port','Destination Port','NAT Source Port','NAT Destination Port']
          ,fix_imbalance = True
          ,normalize = True
          )

# compare models
top3 = compare_models(n_select = 3)

# tune top 3 models
tuned_top3 = [tune_model(i) for i in top3]

# ensemble top 3 tuned models
ensembled_top3 = [ensemble_model(i) for i in tuned_top3]

# blender
blender = blend_models(tuned_top3)

# stacker
stacker = stack_models(tuned_top3)

# check leaderboard
get_leaderboard()

Warning: No categorical columns found. Calling 'transform' will only return input data.

Initiated  . . . . . . . . . . . . . . . . . .                   21:12:00
Status     . . . . . . . . . . . . . . . . . .  Searching Hyperparameters
Estimator  . . . . . . . . . . . . . . . . . .  Extreme Gradient Boosting

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Initiated  . . . . . . . . . . . . . . . . . .              21:24:03
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

Fitting 10 folds for each of 10 candidates, totalling 100 fits

,,
,,
Initiated,. . . . . . . . . . . . . . . . . .,21:28:44
Status,. . . . . . . . . . . . . . . . . .,Searching Hyperparameters
Estimator,. . . . . . . . . . . . . . . . . .,Light Gradient Boosting Machine

Fitting 10 folds for each of 10 candidates, totalling 100 fits

Initiated  . . . . . . . . . . . . . . . . . .              21:30:46
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

Initiated  . . . . . . . . . . . . . . . . . .              22:01:50
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

Initiated  . . . . . . . . . . . . . . . . . .              22:03:52
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

Initiated  . . . . . . . . . . . . . . . . . .              22:04:43
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

Initiated  . . . . . . . . . . . . . . . . . .              22:09:33
Status     . . . . . . . . . . . . . . . . . .  Compiling Estimators
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

Initiated  . . . . . . . . . . . . . . . . . .              22:27:50
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .     Compiling Library

,Model Name,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC
Index,,,,,,,,,
0,Logistic Regression,"(TransformerWrapperWithInverse(exclude=None, i...",0.9195,0.9982,0.9195,0.9895,0.9483,0.8658,0.8732
1,K Neighbors Classifier,"(TransformerWrapperWithInverse(exclude=None, i...",0.9877,0.9974,0.9877,0.9969,0.9920,0.9789,0.9791
2,Naive Bayes,"(TransformerWrapperWithInverse(exclude=None, i...",0.9913,0.9989,0.9913,0.9969,0.9940,0.9851,0.9851
3,Decision Tree Classifier,"(TransformerWrapperWithInverse(exclude=None, i...",0.9969,0.9984,0.9969,0.9973,0.9971,0.9947,0.9947
4,SVM - Linear Kernel,"(TransformerWrapperWithInverse(exclude=None, i...",0.8982,0.0000,0.8982,0.9875,0.9325,0.8320,0.8433
5,Ridge Classifier,"(TransformerWrapperWithInverse(exclude=None, i...",0.7746,0.0000,0.7746,0.9115,0.8109,0.6515,0.6817
6,Random Forest Classifier,"(TransformerWrapperWithInverse(exclude=None, i...",0.9977,0.9998,0.9977,0.9981,0.9979,0.9961,0.9961
7,Quadratic Discriminant Analysis,"(TransformerWrapperWithInverse(exclude=None, i...",0.5768,0.8533,0.5768,0.8024,0.5772,0.3674,0.4613
8,str,"(TransformerWrapperWithInverse(exclude=None, i...",0.9827,0.9969,0.9827,0.9827,0.9825,0.9702,0.9704
9,Gradient Boosting Classifier,"(TransformerWrapperWithInverse(exclude=None, i...",0.9930,0.9998,0.9930,0.9981,0.9953,0.9880,0.9881
10,Linear Discriminant Analysis,"(TransformerWrapperWithInverse(exclude=None, i...",0.7735,0.9899,0.7735,0.9109,0.8100,0.6504,0.6810
11,Extra Trees Classifier,"(TransformerWrapperWithInverse(exclude=None, i...",0.9967,0.9993,0.9967,0.9970,0.9968,0.9943,0.9943
12,Extreme Gradient Boosting,"(TransformerWrapperWithInverse(exclude=None, i...",0.9978,0.9998,0.9978,0.9983,0.9980,0.9963,0.9963
13,Light Gradient Boosting Machine,"(TransformerWrapperWithInverse(exclude=None, i...",0.9975,0.9998,0.9975,0.9982,0.9978,0.9957,0.9957
14,CatBoost Classifier,"(TransformerWrapperWithInverse(exclude=None, i...",0.5983,0.5998,0.5983,0.5988,0.5985,0.5971,0.5971
15,Dummy Classifier,"(TransformerWrapperWithInverse(exclude=None, i...",0.5744,0.5000,0.5744,0.3299,0.4191,0.0000,0.0000
16,Extreme Gradient Boosting,"(TransformerWrapperWithInverse(exclude=None, i...",0.9980,0.9998,0.9980,0.9983,0.9981,0.9965,0.9965
17,Extreme Gradient Boosting,"(TransformerWrapperWithInverse(exclude=None, i...",0.9978,0.9998,0.9978,0.9983,0.9980,0.9963,0.9963
18,Random Forest Classifier,"(TransformerWrapperWithInverse(exclude=None, i...",0.9836,0.9998,0.9836,0.9977,0.9902,0.9718,0.9722
19,Random Forest Classifier,"(TransformerWrapperWithInverse(exclude=None, i...",0.9977,0.9998,0.9977,0.9981,0.9979,0.9961,0.9961
20,Light Gradient Boosting Machine,"(TransformerWrapperWithInverse(exclude=None, i...",0.9977,0.9998,0.9977,0.9981,0.9979,0.9960,0.9960
21,Light Gradient Boosting Machine,"(TransformerWrapperWithInverse(exclude=None, i...",0.9975,0.9998,0.9975,0.9982,0.9978,0.9957,0.9957
22,str,"(TransformerWrapperWithInverse(exclude=None, i...",0.9978,0.9998,0.9978,0.9983,0.9980,0.9962,0.9962
23,str,"(TransformerWrapperWithInverse(exclude=None, i...",0.9977,0.9998,0.9977,0.9981,0.9979,0.9960,0.9960
24,str,"(TransformerWrapperWithInverse(exclude=None, i...",0.9976,0.9998,0.9976,0.9981,0.9978,0.9958,0.9958
25,Voting Classifier,"(TransformerWrapperWithInverse(exclude=None, i...",0.9979,0.9998,0.9979,0.9982,0.9980,0.9964,0.9964
26,Stacking Classifier,"(TransformerWrapperWithInverse(exclude=None, i...",0.9983,0.9997,0.9983,0.9982,0.9983,0.9971,0.9971